# Generated by Django 5.0.7 on 2024-08-23 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('humster', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='humster',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='humster',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='humster.category'),
        ),
        migrations.AddField(
            model_name='humster',
            name='husband',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wuman', to='humster.husband'),
        ),
        migrations.AddField(
            model_name='humster',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='humster.tagpost'),
        ),
        migrations.AddIndex(
            model_name='humster',
            index=models.Index(fields=['-time_create'], name='humster_hum_time_cr_6d5c7f_idx'),
        ),
    ]
